version: "3"

networks:
  default:
    external:
      name: external-example

services:
  msgserver:
    build: "./messaging-service"
    environment:
      NODE_ENV: production
      REDIS_URL: redisCache:6379
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
    ports:
      - 9090:9090
