version: "3"

networks:
  default:
    external:
      name: external-example

services:
  msgserver:
    image: golang:1.20.4
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      # GO111MODULE: true
      NODE_ENV: production
      REDIS_URL: redisCache:6379
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
    ports:
      - 9090:9090
    command: go run main.go
    # command: CGO_ENABLED=0 go build -gcflags "all=-N -l" -o main . && ./main
