version: "3"

networks:
  default:
    external:
      name: chat_api_network

services:
  redisCache:
    container_name: chat_api_redis
    image: "redis:latest"
    ports:
      - 6380:6379
    # healthcheck:
    #   test: ["CMD", "redis-cli", "--raw", "incr", "ping"]

  mysqldb:
    container_name: chat_api_mysqldb
    image: mysql:8.0
    restart: always
    ports:
      - 3310:3306/tcp
    # expose:
    #   - 3310
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_HOST: "%"
    # volumes:
    #   - ./scripts/mysql:/docker-entrypoint-initdb.d
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   timeout: 20s
    #   retries: 10
