version: "3"

services:
  mysqldb:
    container_name: mysqldb_unittest
    image: mysql:8.0
    restart: always
    ports:
      - 3308:3306/tcp
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./scripts/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
